name: pull-request-build

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --stacktrace
      - name: Upload Build Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: build reports
          path: subprojects/core/build/reports
