name: pull-request-build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set env
        run: |
          echo 'OSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }}' >> $GITHUB_ENV
          echo 'OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}' >> $GITHUB_ENV
          echo 'OSSRH_STAGING_PROFILE_ID=${{ secrets.OSSRH_STAGING_PROFILE_ID }}' >> $GITHUB_ENV
          echo 'SIGNING_KEYID=${{ secrets.SIGNING_KEYID }}' >> $GITHUB_ENV
          echo 'SIGNING_PASSWORD=${{ secrets.SIGNING_PASSWORD }}' >> $GITHUB_ENV
          echo 'SIGNING_KEY<<EOF' >> $GITHUB_ENV
          echo '${{ secrets.SIGNING_KEY }}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Gradle clean
        run: |
          ./gradlew clean
      - name: Gradle build
        run: |
          ./gradlew build
      - name: Gradle publish to mavenLocal
        run: |
          ./gradlew publishToMavenLocal
      - name: Gradle publish to nexus-snapshot
        run: |
          ./gradlew publishToSonatype --stacktrace
      - name: Upload Build Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: build_reports
          path: subprojects/core/build/reports
